import os
import inspect
from flask_admin import Admin
from . import models
from .models import db, User, Customer, Owner, Photo, Like, Comment, Point, Restaurant
from flask_admin.contrib.sqla import ModelView
from flask_admin.theme import Bootstrap4Theme


class CustomerView(ModelView):
    column_list = [
        "id",
        "user_id",
        "photos",
        "points"
    ]


class OwnerView(ModelView):
    column_list = [
        "id",
        "user_id",
        "restaurants"
    ]


class PhotoView(ModelView):
    column_list = [
        "id",
        "customer_id",
        "restaurant_id",
        "customer",
        "restaurant",
        "likes",
        "comments"
    ]


class LikeView(ModelView):
    column_list = [
        "id",
        "photo_id",
        "user_id",
        "photo"
    ]


class CommentView(ModelView):
    column_list = [
        "id",
        "comment",
        "photo_id",
        "user_id",
        "photo"
    ]


class PointView(ModelView):
    column_list = [
        "id",
        "customer_id",
        "customer"
    ]


class RestaurantView(ModelView):
    column_list = [
        "id",
        "owner_id",
        "photos",
        "owner"
    ]

def setup_admin(app):
    app.secret_key = os.environ.get('FLASK_APP_KEY', 'sample key')
    app.config['FLASK_ADMIN_SWATCH'] = 'slate'
    admin = Admin(app, name='4Geeks Admin', theme=Bootstrap4Theme(swatch='cerulean'))

    # Add your models here, for example this is how we add a the User model to the admin
    admin.add_view(ModelView(User, db.session))
    admin.add_view(CustomerView(Customer, db.session))
    admin.add_view(OwnerView(Owner, db.session))
    admin.add_view(ModelView(Photo, db.session))
    admin.add_view(ModelView(Like, db.session))
    admin.add_view(ModelView(Comment, db.session))
    admin.add_view(ModelView(Point, db.session))
    admin.add_view(ModelView(Restaurant, db.session))
 
    # You can duplicate that line to add mew models
    # admin.add_view(ModelView(YourModelName, db.session))


# def setup_admin(app):
#     app.secret_key = os.environ.get('FLASK_APP_KEY', 'sample key')
#     admin = Admin(app, name='4Geeks Admin',
#                   theme=Bootstrap4Theme(swatch='cerulean'))
#     admin.add_view(ModelView(Customer, db.session))
#     # Dynamically add all models to the admin interface
#     for name, obj in inspect.getmembers(models):
#         # Verify that the object is a SQLAlchemy model before adding it to the admin.
#         if inspect.isclass(obj) and issubclass(obj, db.Model):
#             # this line was changed by Copilot to the new version below
#             admin.add_view(ModelView(obj, db.session))

#         # if inspect.isclass(obj) and issubclass(obj, db.Model) and name != 'User':
#         #     admin.add_view(ModelView(obj, db.session)) # This line was generated by Copilot and it claims it is necessary to allow the password to be entered for a User. The original version is above.
